### PR TITLE
Add merge support

### PR DESCRIPTION
**Pull request by james2doyle**

### CODE REVIEW

**Comment by brunogaspar** [comment]
This one as well, it seems to have unrelated changes that are on master already.

**Comment by james2doyle** [comment]
Done

**Comment by brunogaspar** [comment]
I've updated the base branch on the PR to be the `master`, but it seems that it messed up the tests.

Also, the `...` token isn't supported on PHP 5.4 only on PHP 5.6.

If you're willing to submit a new PR i would appreciate it (it can contain the changes from the other PR as well), otherwise i'll look into adding the required changes at a later time, but i don't think it's fair to add them by myself and you lose the credit.

**Comment by james2doyle** [comment]
To be frank, I don't think I will be submitting another PR. These have been open for a while and haven't been addressed, so I have been using my own fork as a local package in my composer.json.

You can merge them if you'd like. The lost credit is fine with me.

**Comment by brunogaspar** [comment]
Will be closing then, since these have unrelated changes.

Thanks though, will add the changes when i have a bit more time.

**Pull request closed without merging**
